resolver: ghc-9.2.8

packages:
  - ./cabal-pkg-config-version-hook
  - ./hercules-ci-agent
  - ./hercules-ci-api-agent
  - ./hercules-ci-api-core
  - ./hercules-ci-api
  - ./hercules-ci-cli
  - ./hercules-ci-cnix-expr
  - ./tests/agent-test
  - ./hercules-ci-cnix-store

  # incorporate into "local" build so the tooling doesn't get confused by the
  # local -> snapshot -> local dependency, such as agent -> cachix -> cnix-store
  - ./dev/vendor/cachix/cachix
  - ./dev/vendor/cachix/cachix-api

system-ghc: true

extra-deps:
  - ascii-progress-0.3.3.0@sha256:bdcdfabdd2f3e8de0cec4ea058810a77dd8b79506fc0cf90efb93ee9f99ff8e3,4168
  - concurrent-output-1.10.17@sha256:5b5d8d384dda22283b49c9ed35ca4f02a96f5cfed12b28160a341708d1177bf3,1678
  - terminal-size-0.3.4@sha256:f0318c54273d04afb65109683b442792dcb67af1ad01ab5ec64423a28bb97715,1291

flags:
  hercules-ci-cnix-store:
    ide: true
  hercules-ci-cnix-expr:
    ide: true
  hercules-ci-agent:
    ide: true

nix:
  enable: false
  packages: []
  shell-file: ./shell.nix

build:
  # this makes the stack repl-based lsp logic work for tests
  test: true
